---
baseURL: 'https://www.kautsya.in'
relativeURLs: true
canonifyurls: true
enableRobotsTXT: true
languageCode: en-us
metaDataFormat: yaml
pygmentsCodeFences: true
pygmentsStyle: emacs

author: Kautsya Kanu
title: Kautsya Kanu
theme: goa

blackfriday:
  hrefTargetBlank: true

params:
  intro: Kautsya Kanu
  description: iOS, Algorithms, Machine Learning, Natural Language Processing, Computer Vision
  authorimage: authorImage.jpg
  enableRSS: true
  dateFormat: 'Jan 2, 2006'
  extra:
    copyright: '&copy; 2019. Kautsya Kanu.'
    poweredBy: true
    facebookProfileId: 1233718306710372
  social:
    github: kautsiitd
    stackoverflow: 4614493/kautsya-kanu?tab=profile
    codeChef: kauts_kanu
    codeChefDiscuss: 70101/kauts_kanu
    linkedin: kautsya-kanu-a0328293
    facebook: kautsya.kanu
    email: kautsiitd@gmail.com
menu:
  main:
    - name: Resume
      identifier: resume
      url: /files/Resume.pdf
      weight: 1
